### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by MorgenAnSpyrys** [MichaelDeng03/osu_oracle2#2]
Hi there,
I was interested in forking the program but currently there is no License in place, meaning any forks would constitute Copyright infringement. Please add some kind of License to the project.
Here's a quick guide on how to do that by GitHub:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Popular Licenses include the GNU Public License (2.0, 3.0 or derivates such as the AGPL or LGPL), the MIT License, the Mozilla Public License (MPL), and more.

**Comment by MichaelDeng03** [comment]
Just added MIT License
